spring.application.name=GitSocial
# Spring Boot'a .env dosyas?n? okumas?n? söylüyoruz
spring.config.import=optional:file:../../.env[.properties]

# De?erleri .env dosyas?ndaki isimlerle ça??r?yoruz
spring.datasource.url=jdbc:postgresql://localhost:${LOCAL_DB_PORT}/gitsocial_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect