spring.application.name=GitSocial

spring.config.import=optional:file:../../.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:${LOCAL_DB_PORT}/gitsocial_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
app.security.jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}